### PR TITLE
Initial writeup for policies-runtime/app-embedded 

### PR DESCRIPTION
**Pull request by KICKdesigns**
Will add the PUT and POST next week. This is just to get some inital verbiage for the template(s)

### CODE REVIEW

**Comment by iansk** [comment]
@KICKdesigns I made a small change to the desc for the GET endpoint. The rest looks good to me.

**Comment by KICKdesigns** [comment]
@iansk See additions for PUT and POST. Note: Need to modify based on where the POST in the Console UI is (I can't find the location).

**Comment by iansk** [comment]
@KICKdesigns Looks good to me. Two small changes:

* Let's use the `alert` actions by default for all example curl commands. Customers build their way up to `block` and `prevent` actions because they can have severe adverse impact on operations.
* Runtime POST endpoints aren't being used by our UI, so I hid them by adding them to `suppress.cfg`. No need to document them for the `policies/runtime/*` endpoints.

**Comment by iansk** [comment]
@KICKdesigns Merging this now.

**Pull request merged**
