### PR TITLE
Updates readme for local builds and removes .DStore

### PR DESCRIPTION
**Pull request by emanic**
- Adds files and instructions so contributors can make local builds

### CODE REVIEW

**Comment by iansk** [comment]
@emanic This PR touches 54 files! Please fix it up, and resubmit.

**Comment by emanic** [comment]
I think they are required @iansk

**Comment by iansk** [comment]
@emanic Yup, you're right.

**Comment by iansk** [comment]
@emanic I worked on your branch a bit, and merged it into master already. Can you check out master and make sure it works for you? Once you verify, I'll close this PR.

**Comment by iansk** [comment]
See the updated and merged PR here: https://github.com/twistlock/docs/pull/96

**Comment by emanic** [comment]
OK thanks @iansk I'll take a look 👍

**Comment by emanic** [comment]
@iansk OK I rebased this off the latest master and updated the README.md. New build.sh runs much better. Thanks... Can you review this PR again? I see you added a bunch of files, but I still have some here in this PR. I think we may need these.

**Comment by iansk** [comment]
@emanic My merged branch (now in master) was based off this branch, so it contains all the files you added. I moved some files around to make the repo cleaner. Please incorporate my work in this branch by either rebasing this branch off of master, or merging master in your branch. Once you've done this, I'll merge your PR.

**Comment by emanic** [comment]
@iansk OK yeah I did rebase it, but it looks like you renamed the `files` directory and that didn't get picked up. So I think this should be what we need then.

**Comment by emanic** [comment]
OK nvm, I see that you moved the gem and python script into `_build`. OK maybe you can take a look now.

**Pull request merged**
