### PR TITLE
Initial writeups for offline endpoints - see note

### PR DESCRIPTION
**Pull request by KICKdesigns**
The preview isn't working. I've added the new upload endpoint to the topic map and the api JSON, but it doesn't seem to be working. Also, see Google spreadsheet for questions about the writeups for both of these endpoints.

### CODE REVIEW

**Comment by iansk** [comment]
@KICKdesigns We've explicitly hidden this endpoint in the API docs. Check out `_build/suppress.cfg`. There are some endpoints which are built to support the UI only, and it's confusing for them to be part of the reference that customers can program against, so we hide it.

We also sometimes hide endpoints because there's a better way to automate things. In this case, we've got a command line utility called `twistcli` which has two functions for managing threat data:

`./twistcli intelligence download`
`./twistcli intelligence upload`

Here's the background info on what we're trying to help customers resolve:

We've got many customers that operate our software in an air-gapped/regulated environments. These customers need a way to update Consoles' Intelligence Steam data when their Console is unable to communicate directly to the Internet and connect to the Intelligence Stream data itself. Our intel stream can publish updated threat/vuln data up to several times per day, and customers want to get access to it as soon as possible. Using `twistcli` is the preferred approach to automating the process of "getting a copy of the threat data from an internet connected location" and then "uploading the latest threat data package to the air-gapped Console".

In answer to your questions in the spreadsheet, there's no need to document either of these endpoints:

`/api/v1/feeds/offline/refresh`
`/api/v1/feeds/offline/{id}`

**Comment by KICKdesigns** [comment]
@iansk thanks for the add endpoint info. As for these two specific endpoints, they were in the spreadsheet list - can we confirm the list is accurate for the endpoints that need to be done?

**Comment by iansk** [comment]
@KICKdesigns My bad. I'll clean out the suppress endpoints from our spreadsheet.

**Comment by iansk** [comment]
@KICKdesigns I'm going to leave this one unmerged (and probably delete the PR shortly) since we don't need to document these endpoints.

**Comment by iansk** [comment]
Closing unmerged.

**Pull request closed without merging**
