### PR TITLE
Created a new doc for High Availability and Disaster Recovery guidelines

### PR DESCRIPTION
**Pull request by grevach**
- New doc to cover our guidelines for high availability and disaster recovery.
- Added links to the new article from the reference architecture.

### CODE REVIEW

**Comment by iansk** [comment]
@grevach Thanks for doing this work. This is an excellent addition to our doc set. Couple of questions:

1. Did you manage to revalidate the steps in the multi-AZ article end-to-end? Part of the reason I took it down is because there were complaints that it wasn't working.

2. I agree that disaster recovery is essential to HA, and it should be discussed as part of this article. But would you be open to moving the procedural sections ("Configuring automated backups", "Making manual backups", and "Restoring backups from the Console UI") back to their own article under the Configure section? We'd keep the "Prisma Cloud Compute backup & restore" section here, and then link to the procedural bits for more info.

Since we support backup and restore for both SaaS and self-hosted, I'd like to keep the procedural sections generic for both product variations. And then this article would be published for self-hosted only.

**Comment by grevach** [comment]
Thanks @iansk 

1. I thought QA validated it (because they tested using EFS cross AZ for Salesforce), but checking this again, they didn't validate it with the procedure described in the article. Therefore I removed the article again and just mentioned EFS as an example for shared storage.
2. I split the articles again according to your suggestion, and added links to the backup & restore article from the HA & DR article. One question - how do I make the HA & DR article available only for the Self-hosted docs?

Thanks!

**Review by morellonet — COMMENTED** [review]
Good work @grevach!  Made a few minor changes, but thanks for leading this

**Comment by iansk** [comment]
Thanks @grevach. I'm merging this now.

Quick note that I needed to change the name of backup and restore article back to `configure/disaster_recovery.adoc` from `configure/backup_and_restore.adoc`.

Contextual help links are hard-coded into Console, and if we change the file name, we'll break those links. Fortunately, we can separately configure the rendered name for a given file, so when customers load the page, it'll say "Backup and restore".

**Review by iansk — APPROVED** [review]

**Pull request merged**
