### PR TITLE
API Endpoint description rewrite / formatting

### PR DESCRIPTION
**Pull request by KICKdesigns**

### CODE REVIEW

**Comment by iansk** [comment]
@KICKdesigns Looks good!

One comment:

We've got two versions of our software: self-hosted (the version you've got) and SaaS. For self-hosted, it's obvious which URL you need to hit to access the API: it's the IP address of the host where Console runs, or the DNS name of the machine, or the DNS name of the load balancer in front. Also by default, we serve the API on port 8083.

In SaaS, we run the Console for you. In SaaS. To get your API address, you need to log into Console to get the URL string. See the instructions here:

https://docs.twistlock.com/docs/enterprise_edition/api/access_api.html

Here's a screenshot of what it looks like:

getting_saas_console_api_address

Since we developed the self-hosted version of the software first, most of our docs are geared towards self-hosted. This is confusing to new customers who have just recently signed up for the SaaS version of Console. In particular, the port 8083 is confusing to SaaS customers because their Console UI and API is served on port 443.

As you're working on updating our API docs, can you please:

1. Update the curl commands so that the URL in the curl commands just generically refers to `<CONSOLE>` and drop the port number.

2. Add a section in `descriptions/gettingStarted.md` that describes how to evaluate `<CONSOLE>` for your environment. You can re-use a lot of our existing docs for this. See:

SaaS: https://docs.twistlock.com/docs/enterprise_edition/api/access_api.html

and

Self-hosted: https://docs.twistlock.com/docs/compute_edition/api/access_api.html

Let me know if you've got any questions.

**Comment by iansk** [comment]
@KICKdesigns I made a small change to our Python script (twapi_gen.py). The script gets the min role required to access each endpoint from the API JSON and appends it to the end of the endpoint description. I've updated the Python script to specify this min role under a level 3 heading to mirror the format you want to adopt.

Without my update:

before_ping

With my update:

after_ping

**Comment by iansk** [comment]
@KICKdesigns Also, as we discussed, please remove the section on response codes.

The table looks great though...hopefully you can find some other places to use it.

**Comment by KICKdesigns** [comment]
@iansk I can confirm the published version includes the role now. The response section removal has also been pushed to the repo.

**Review by iansk — APPROVED** [review]

**Comment by iansk** [comment]
Thanks @KICKdesigns. This one is now merged.

**Pull request merged**
