### PR TITLE
serverless twistcli scan updates

### PR DESCRIPTION
**Pull request by joshfalgout**
Removed --ci references for serverless twistcli scan

### CODE REVIEW

**Comment by joshfalgout** [comment]
Documented twistcli serverless scan parameters

**Comment by joshfalgout** [comment]
Modified text around the Jenkins plugin integration and the use of some of these parameters.

**Comment by joshfalgout** [comment]
Fixes #61

**Comment by iansk** [comment]
Looks good to me. Thanks, @joshfalgout. Merging this now.

**Pull request merged**
