### PR TITLE
ecs install updates

### PR DESCRIPTION
**Pull request by joshfalgout**
Simplified install process
Modified 20.04 install instructions - excludes cert requirements
Updated the task definition for defenders to be simplified - removed null values

### CODE REVIEW

**Comment by joshfalgout** [comment]
@iansk please also update the CDN for https://cdn.twistlock.com/docs/attachments/amazon-ecs-compute-defender.json

**Comment by sgordon46** [comment]
Good update @joshfalgout glad we got this working.  Did it work fine for the SaaS deployment as well?

**Comment by joshfalgout** [comment]
@sgordon46 corrected the cURL commands for PCEE.  Just verified this flow

**Comment by iansk** [comment]
Thanks for your work on this @joshfalgout. It's merged now, it'll be live tomorrow. I've uploaded the updated defender JSON attachment.

**Pull request merged**
