### PR TITLE
Openshift Updates

### PR DESCRIPTION
**Pull request by automatecloud**
Fixed the following:
1. Better structure of the Installation flow with integration of YAML and Helm Chart in one flow and not different chapters.
2. Added all necessary changes for Openshift 4 where CRI-O is a must.
3. Added the necessary changes for the Defenders if they are deployed as a helm chart in Openshift 4.
4. Added PSP example to the installation of Kubernetes

### CODE REVIEW

**Comment by ryanchauvin** [comment]
@iansk this is ready to merge

**Comment by ryanchauvin** [comment]
@iansk could you please look at merging this one as well? It's showing a conflict, not sure how to fix that.

**Comment by sgordon46** [comment]
@automatecloud there is a merge conflict with this one.  Can you fix?

**Comment by automatecloud** [comment]
@sgordon46 i did a complete rewriting of the openshift installation back in May - July that should be merged before we merge all other openshift updates if you ask me? @iansk what can we do now?

**Comment by ryanchauvin** [comment]
@automatecloud do you have a PR for those changes?

**Comment by automatecloud** [comment]
@ryanchauvin no but i think we can use yours ? https://github.com/twistlock/docs/issues/148

**Comment by iansk** [comment]
Excellent work @automatecloud. I'm merging a variation of your work in this PR: https://github.com/twistlock/docs/pull/239

@Also, thanks @ryanchauvin for additional follow-on fixes. 

Closing unmerged.

**Pull request closed without merging**
