### PR TITLE
Initial changes for API spec post

### PR DESCRIPTION
**Pull request by KICKdesigns**
@iansk I wanted to send this one over so you can see if the <Swagger/OpenAPI spec> placeholder will work or if you want to use a specific spec in the example.

### CODE REVIEW

**Comment by KICKdesigns** [comment]
@iansk Sorry about this one - I just realized you changed the list and removed some of the endpoints. Making a note of it now.

**Comment by iansk** [comment]
@KICKdesigns No worries. I'll send you an email about this now.

**Comment by KICKdesigns** [comment]
@iansk Note the following observations:

- POST /api/v1/policies/firewall/app/apispec is invoked when the a Swagger file is imported via the "Import" button on the "Create new WAAS app" popup. It's body is swagger content. Using the PetStore swagger works both in the UI and when invoking the endpoint from command line.
- PUT api/v1/policies/firewall/app/app-embedded is invoked when clicking "Save" on the "Create new WAAS app" popup. Its body includes an WAAS.apiSpec returned from the previous endpoint
- no APIs are invoked on that popup when adding an endpoint ("Endpoint setup" subtab) or adding API protection ("API protection" subtab) within the dialog

I've used a pruned down Swagger example for the example request in the markdown that was pulled from the web, because it's much shorter than a pruned down PetStore example.

**Comment by KICKdesigns** [comment]
@iansk For Hamilton's OpenAP definitionI, we currently have waas.APISpec and sub objects documented in two separate spreadsheets /policies/firewall/app/* tab and /policies/firewall/app/app-embedded tab. I've compared Hamilton's spec to that in openapi_21_01_640_formatted.json and made the following updates:

- Added additional values to enum: waas.ParamLocation to both spreadsheets
- Updated waas.Param's description of "location" field based on new values for waas.ParamLocation in both spreadsheets
- Added missing value "pipeDelimited" to waas.ParamStyle in /policies/firewall/app/*
- Added new value "object" to waas.ParamType enum in both spreadsheets

I left the original param spreadsheets in case we need them and labelled the new ones with (Hamilton) in the tab name.

**Review by iansk — APPROVED** [review]

**Review by iansk — APPROVED** [review]

**Pull request merged**
