### PR TITLE
Clarify how Fargate tasks are specified in collections.

### PR DESCRIPTION
**Pull request by iansk**

### CODE REVIEW

**Comment by iansk** [comment]
@MorShabiPAN Based on your other PR, I also added this update to our collections article. I think your screenshot was valuable for helping customers visualize how the Hosts field is used to specify Fargate tasks.

**Review by MorShabiPAN — COMMENTED** [review]
But we should specify that the Fargate collection is by host only for Vuls and compliance.
In Runtime, the customer should create the Fargate tasks collection using the AppID field

**Comment by iansk** [comment]
Thanks @MorShabiPAN 

Does this look better?

https://github.com/twistlock/docs/commit/ff1875ec56d0fa3b6f6baf11a8370d7e419a673a

**Comment by MorShabiPAN** [comment]
Yes, thanks a lot @iansk :)

**Pull request merged**
