### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MayaShani**
This is the full description list of the attack explorer techniques with their description
Need also to link to it from the attack doc,  @iansk  - can you please add it as part of this commit?

### CODE REVIEW

**Comment by sgordon46** [comment]
This is in docx format, this should be converted to PDF for distribution.
I’m sure Ian would take care of that part.

On Wed, Jun 30, 2021 at 1:56 AM Maya Even-Shani ***@***.***>
wrote:

> This is the full description list of the attack explorer techniques with
> their description
> Need also to link to it from the attack doc, @iansk
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_iansk&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=QwzG-XtNAtDCuAr73QU_gUuAz_LPcFMa5wBXJByECcM&m=1hwprlpawcm59TXlmix23Y637GWeOrl-tsLRZE3PIVc&s=CUKCKRjgmFDL7hGnGuezNNrf9ATUajUh6w5IQ54abMQ&e=>
> - can you please add it as part of this commit?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/twistlock/docs/pull/588
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_twistlock_docs_pull_588&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=QwzG-XtNAtDCuAr73QU_gUuAz_LPcFMa5wBXJByECcM&m=1hwprlpawcm59TXlmix23Y637GWeOrl-tsLRZE3PIVc&s=WPycUI8zO4QHBytpFBjLrYCamMIgDxf9T_PBkUkw7UU&e=>
> Commit Summary
>
>    - Add files via upload
>
> File Changes
>
>    - *A* admin_guide/runtime_defense/Full Attack Explorer Matrix.docx
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_twistlock_docs_pull_588_files-23diff-2D8585b80fb0163692fe685462278ca0b3b8b79342d19db18604b6ee994b4078d2&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=QwzG-XtNAtDCuAr73QU_gUuAz_LPcFMa5wBXJByECcM&m=1hwprlpawcm59TXlmix23Y637GWeOrl-tsLRZE3PIVc&s=jnDRBxfekBJBFe6EL1IsQwITH9HvQjop6H1D0N8O3A8&e=>
>    (0)
>
> Patch Links:
>
>    - https://github.com/twistlock/docs/pull/588.patch
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_twistlock_docs_pull_588.patch&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=QwzG-XtNAtDCuAr73QU_gUuAz_LPcFMa5wBXJByECcM&m=1hwprlpawcm59TXlmix23Y637GWeOrl-tsLRZE3PIVc&s=HNOPoSwiK9tYcBv7qZ-aQGoFJGuizGTNP-cwx6uxi_A&e=>
>    - https://github.com/twistlock/docs/pull/588.diff
>    <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_twistlock_docs_pull_588.diff&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=QwzG-XtNAtDCuAr73QU_gUuAz_LPcFMa5wBXJByECcM&m=1hwprlpawcm59TXlmix23Y637GWeOrl-tsLRZE3PIVc&s=H4mC63yoQa6bjinqIpOXxcU7XC7sFglt3zHr5fECZVU&e=>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_twistlock_docs_pull_588&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=QwzG-XtNAtDCuAr73QU_gUuAz_LPcFMa5wBXJByECcM&m=1hwprlpawcm59TXlmix23Y637GWeOrl-tsLRZE3PIVc&s=WPycUI8zO4QHBytpFBjLrYCamMIgDxf9T_PBkUkw7UU&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAIPXBYG5DB3OHBYVZ4VGTLTVK52FANCNFSM47RVZVPA&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=QwzG-XtNAtDCuAr73QU_gUuAz_LPcFMa5wBXJByECcM&m=1hwprlpawcm59TXlmix23Y637GWeOrl-tsLRZE3PIVc&s=LXvFDZ5RB8ew1b0g6gGHyDPJvyHakQ17Ls7IatqVYzM&e=>
> .
>
-- 

Stephen Gordon |  Systems Engineer, Prisma Cloud

Palo Alto Networks | 3000 Tannery Way | Santa Clara, CA 95054 | USA

Mobile: (504) 729-8110 | ***@***.***
***@***.***>



    <https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>
<https://twitter.com/PaloAltoNtwks>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by reply
e-mail. Any unauthorized use or distribution of the content of this message
is prohibited.

**Comment by MayaShani** [comment]
@iansk - can you please commit this? I have a customer waiting for this

**Comment by iansk** [comment]
@MayaShani Yes, doing this now.

**Comment by iansk** [comment]
@MayaShani Merging and publishing this now.

**Review by iansk — APPROVED** [review]

**Pull request merged**
