### PR TITLE
update opa template

### PR DESCRIPTION
**Pull request by sgordon46**
#19 

update OPA template to match what is in the console.

### CODE REVIEW

**Comment by iansk** [comment]
@sgordon46 I'm wondering if there's a good reason for including the v1.13-v1.15 template in the docs. Customers can get it from the advanced settings dialog. If the devs change the template, our docs immediately go out of date again. IMHO, it's preferable to leave it out.

WDYT?

**Comment by turbodog** [comment]
What about the opposite, where the template lives in the docs and isn't in the product? Argument for that would be the docs are easier to change and explain differences between versions.

**Comment by iansk** [comment]
I actually like it in the product. If you're a customer, you don't have to leave the Console UI to get a pretty critical part of the setup flow. 

I do see your point though. I'm not opposed to keeping the v1.13-1.15 snippet here, but I don't see that the docs offers any additional value in its current form (e.g. explaining the fields, describing tradeoffs or tweaks you could make, etc).

**Comment by sgordon46** [comment]
I like it in the product as well. We can go back down to 1 snipped in the docs,  but we should have the accurate snippet if so.  The questions around yaml and versions have been somewhat common, and the template is a bit quirky to read in the product.  

I'm indifferent to how we do it, but we just need to make it as clear as possible for customers.

**Comment by iansk** [comment]
@sgordon46 Good point. I reworked the article to make it more clear that v1.13-1.15 need one YAML and v1.16+ needs a different YAML. I left both snippets in.

@turbodog Thanks for your input.

Merging this now. It'll be live on docs.tw tonight.

**Pull request merged**
